### PR TITLE
Simplified Chinese translate update

### PR DESCRIPTION
**Pull request by sotux**
Fix many translation mistakes in the exist file.
1. The exist translation is Traditional Chinese but not Simplified Chinese.
2. Fix many variables error in exist file.
3. Update many untranslated entries.

### CODE REVIEW

**Comment by rostovtsev** [comment]
Hi, that you very much. This is great. One thing - is there a way you could provide non-sorted file lines?  ..or you first sorted it and then translated it?

**Comment by sotux** [comment]
I use webmin [translator module](http://wbmtranslator.labs.libre-entreprise.org/), this tool sorts the file automatically. Should I provide an non-sorted file?

**Comment by rostovtsev** [comment]
If you could and if it doesn't take too much of your time, then yes please.

**Comment by sotux** [comment]
OK, I will update it when I done.

**Comment by rostovtsev** [comment]
Thank you!

**Comment by sotux** [comment]
I've reorder the file as the order in en.UTF-8. Please review, thanks.

**Comment by rostovtsev** [comment]
Awesome! Thank you!

**Pull request merged**
