### PR TITLE
German Translations

### PR DESCRIPTION
**Pull request by gnadelwartz**

### CODE REVIEW

**Comment by rostovtsev** [comment]
Thank you very much!

**Comment by rostovtsev** [comment]
The word "notifications" is still to big.

image

**Comment by rostovtsev** [comment]
What about using _**Mitteilung**_ word instead?

**Comment by gnadelwartz** [comment]
ok, this the answer to the question I wanted to ask 😁
if its only for a shorter word: Nachrichten or Meldungen (if 1st is to long 
also)


what line in the lang file I hafe to change?


kay



Am 2. März 2019 7:19:53 nachm. schrieb Ilia Rostovtsev 
<notifications@github.com>:

**Comment by rostovtsev** [comment]
The word `Meldungen` would fit.

I suppose this line?
https://github.com/authentic-theme/authentic-theme/blob/master/lang/de.UTF-8#L548

**Comment by rostovtsev** [comment]
There https://github.com/authentic-theme/authentic-theme/commit/3cdb8dbc4ab32fd3324936f879bd3fd44e1c480a.

**Pull request merged**
